#!/bin/bash

# This script sends desktop notifications.
# This is a helper script. You can send notifications from a cronjob.
# This script require the packge "libnotify-bin".

MAIN_PROCESS="Xwayland"
SESSION_USER=""
MESSAGE=""

function show_usage() {
  printf "\n"
  printf "Send desktop notification.\n"
  printf "This is a helper script. You can send notifications from a cronjob.\n"
  printf "\n"
  printf "Usage:\n"
  printf "%s\n" "  $0 [options [parameters]]"
  printf "Example:\n"
  printf "%s\n" "  $0 --user <username> --message \"<message>\""
  printf "\n"
  printf "Options:\n"
  printf "%s\t%s\t%s\n" "  -u" "--username" "Username of current session"
  printf "%s\t%s\t%s\n" "  -n" "--message" "Specifies the notification text"
  printf "%s\t%s\t\t%s\n" "  -h" "--help" "Print help"
  printf "\n"

  return 0
}

while [ -n "$1" ]; do
  case $1 in
    --user|-u)
      shift
      SESSION_USER="$1"
    ;;
    --message|-m)
      shift
      MESSAGE="$1"
    ;;
    *)
      show_usage
      exit 0
    ;;
  esac
  shift
done

if [ -z "$SESSION_USER" ]; then
  show_usage
  echo "ERROR: Missing -u, --user option."
  exit 1
fi
if [ -z "$MESSAGE" ]; then
  show_usage
  echo "ERROR: Missing -m, --message option."
  exit 1
fi

pid=$(pgrep -u "$SESSION_USER" "$MAIN_PROCESS")
dbus=$(sed 's/\o0/\n/g' < "/proc/$pid/environ" | grep "DBUS_SESSION_BUS_ADDRESS" | sed 's/DBUS_SESSION_BUS_ADDRESS=//')
export DBUS_SESSION_BUS_ADDRESS=$dbus

/usr/bin/notify-send "$MESSAGE"

exit 0
